// ignore_for_file: constant_identifier_names

enum Keyboard {
  Left("0x25", false),
  Up("0x26", false),
  Right("0x27", false),
  Down("0x28", false),
  A("0x41", false),
  B("0x42", false),
  C("0x43", false),
  D("0x44", false),
  E("0x45", false),
  F("0x46", false),
  G("0x47", false),
  H("0x48", false),
  I("0x49", false),
  J("0x4A", false),
  K("0x4B", false),
  L("0x4C", false),
  M("0x4D", false),
  N("0x4E", false),
  O("0x4F", false),
  P("0x50", false),
  Q("0x51", false),
  R("0x52", false),
  S("0x53", false),
  T("0x54", false),
  U("0x55", false),
  V("0x56", false),
  W("0x57", false),
  X("0x58", false),
  Y("0x59", false),
  Z("0x5A", false),
  D0("0x30", false),
  D1("0x31", false),
  D2("0x32", false),
  D3("0x33", false),
  D4("0x34", false),
  D5("0x35", false),
  D6("0x36", false),
  D7("0x37", false),
  D8("0x38", false),
  D9("0x39", false),
  NumPad0("0x60", false),
  NumPad1("0x61", false),
  NumPad2("0x62", false),
  NumPad3("0x63", false),
  NumPad4("0x64", false),
  NumPad5("0x65", false),
  NumPad6("0x66", false),
  NumPad7("0x67", false),
  NumPad8("0x68", false),
  NumPad9("0x69", false),
  F1("0x70", false),
  F2("0x71", false),
  F3("0x72", false),
  F4("0x73", false),
  F5("0x74", false),
  F6("0x75", false),
  F7("0x76", false),
  F8("0x77", false),
  F9("0x78", false),
  F10("0x79", false),
  F11("0x7A", false),
  F12("0x7B", false),
  Multiply("0x6A", false),
  Add("0x6B", false),
  Separator("0x6C", false),
  Subtract("0x6D", false),
  Decimal("0x6E", false),
  Divide("0x6F", false),
  CapsLock("0x14", false),
  Tab("9", false),
  Return("0xD", false),
  Enter("0xD", true),
  Space("0x20", false),
  PageUp("0x21", false),
  PageDown("0x22", false),
  End("0x23", false),
  Home("0x24", false),
  Insert("0x2D", false),
  Backspace("8", false),
  Delete("0x2E", false),
  // None("0", false),
  // LButton("1", false),
  // RButton("2", false),
  // Cancel("3", false),
  // MButton("4", false),
  // XButton1("5", false),
  // XButton2("6", false),
  // LineFeed("0xA", false),
  // Clear("0xC", false),
  // Shift("0x10", false),
  // Control("0x11", false),
  // Alt("0x12", false),
  // Menu("0x12", false),
  // Pause("0x13", false),
  // Capital("0x14", false),
  // KanaMode("0x15", false),
  // HanguelMode("0x15", false),
  // HangulMode("0x15", false),
  // JunjaMode("0x17", false),
  // FinalMode("0x18", false),
  // HanjaMode("0x19", false),
  // KanjiMode("0x19", false),
  // Escape("0x1B", false),
  // IMEConvert("0x1C", false),
  // IMENonconvert("0x1D", false),
  // IMEAccept("0x1E", false),
  // IMEAceept("0x1E", false),
  // IMEModeChange("0x1F", false),
  // Next("0x22", false),
  // Prior("0x21", false),
  // Select("0x29", false),
  // Print("0x2A", false),
  Execute("0x2B", false),
  // PrintScreen("0x2C", false),
  // Snapshot("0x2C", false),
  // LWin("0x5B", false),
  // RWin("0x5C", false),
  // Apps("0x5D", false),
  // Sleep("0x5F", false),
  // Help("0x2F", false),
  // F13("0x7C", false),
  // F14("0x7D", false),
  // F15("0x7E", false),
  // F16("0x7F", false),
  // F17("0x80", false),
  // F18("0x81", false),
  // F19("0x82", false),
  // F20("0x83", false),
  // F21("0x84", false),
  // F22("0x85", false),
  // F23("0x86", false),
  // F24("0x87", false),
  // NumLock("0x90", false),
  // Scroll("0x91", false),
  // LShift("0xA0", false),
  // LShiftKey("0x10", false),
  // RShift("0xA1", false),
  // RShiftKey("0x10", false),
  // LControl("0xA2", false),
  // LControlKey("0xA2", false),
  // RControl("0xA3", false),
  // RControlKey("0xA3", false),
  // LAlt("0xA4", false),
  // LMenu("0xA4", false),
  // RMenu("0xA5", false),
  // RAlt("0xA5", false),
  // BrowserBack("0xA6", false),
  // BrowserForward("0xA7", false),
  // BrowserRefresh("0xA8", false),
  // BrowserStop("0xA9", false),
  // BrowserSearch("0xAA", false),
  // BrowserFavorites("0xAB", false),
  // BrowserHome("0xAC", false),
  // VolumeMute("0xAD", false),
  // VolumeDown("0xAE", false),
  // VolumeUp("0xAF", false),
  // MediaNextTrack("0xB0", false),
  // MediaPreviousTrack("0xB1", false),
  // MediaStop("0xB2", false),
  // MediaPlayPause("0xB3", false),
  // LaunchMail("0xB4", false),
  // SelectMedia("0xB5", false),
  // LaunchApplication1("0xB6", false),
  // LaunchApplication2("0xB7", false),
  // OemSemicolon("0xBA", false),
  // Oem1("0xBA", false),
  // Oemplus("0xBB", false),
  // Oemcomma("0xBC", false),
  // OemMinus("0xBD", false),
  // OemPeriod("0xBE", false),
  // OemQuestion("0xBF", false),
  // Oem2("0xBF", false),
  // Oemtilde("0xC0", false),
  // Oem3("0xC0", false),
  // OemOpenBrackets("0xDB", false),
  // Oem4("0xDB", false),
  // OemPipe("0xDC", false),
  // Oem5("0xDC", false),
  // OemCloseBrackets("0xDD", false),
  // Oem6("0xDD", false),
  // OemQuotes("0xDE", false),
  // Oem7("0xDE", false),
  // Oem8("0xDF", false),
  // OemBackslash("0xE2", false),
  // Oem102("0xE2", false),
  // ProcessKey("0xE5", false),
  // Packet("0xE7", false),
  // Attn("0xF6", false),
  // Crsel("0xF7", false),
  // Exsel("0xF8", false),
  // EraseEof("0xF9", false),
  // Play("0xFA", false),
  // Zoom("0xFB", false),
  // NoName("0xFC", false),
  // Pa1("0xFD", false),
  // OemClear("0xFE")
  ;

  const Keyboard(this.value, this.extended);
  final String value;
  final bool extended;
}
